version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
      - DNS_TIMEOUT=${DNS_TIMEOUT}
      - DNS_LIFETIME=${DNS_LIFETIME}
      - DNS_TRIES=${DNS_TRIES}
      - DNS_NAMESERVERS=${DNS_NAMESERVERS}
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 